version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - application-network

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    ports:
      - "19092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:22181'
      # Set replicationFactor = 1 is required when you are running with a single-node cluster. If you have three or more nodes, you can use the default.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:9092,EXTERNAL://localhost:19092
    networks:
      - application-network

  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop
    restart: "no"
    depends_on:
      - broker
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: broker:9092
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    networks:
      - application-network

  producer:
    container_name: producer
    image: producer
    depends_on:
      - zookeeper
    ports:
      - "8081:8080"
    build:
      context: producer
    networks:
      - application-network

  stream-processor:
    container_name: stream-processor
    image: stream-processor
    depends_on:
      - zookeeper
    build:
      context: stream-processor
    networks:
      - application-network

  honda-sales-consumer:
    container_name: honda-sales-consumer
    image: honda-sales-consumer
    depends_on:
      - zookeeper
    build:
      context: honda-sales-consumer
    networks:
      - application-network

  dealership-sales-consumer:
    container_name: dealership-sales-consumer
    image: dealership-sales-consumer
    depends_on:
      - zookeeper
    build:
      context: dealership-sales-consumer
    networks:
      - application-network

networks:
  application-network:
      driver: bridge